### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by Herbstein** [KcYoung1997/PubgReplayManager#1]
Parroting something already said on [reddit](https://www.reddit.com/r/PUBATTLEGROUNDS/comments/7k3cvz/pubgreplaymanager_a_simple_tool_to_backup_pubg/drbku9o/). You really, really need to add a license. I would love to work on this, but I'm not going to do any work without knowing the rights I have with regards to my code.

**Comment by KeiranY** [comment]
Done, added GNU GPL since it seems pretty damn open. If there is any issues with that let me know.

**Comment by Herbstein** [comment]
Seems good to me. Do you have any ideas for taking this further?

**Comment by KeiranY** [comment]
It would be nice to allow the user to set their own replays directory. Maybe add a settings window to show current directory and allow selection of a new one.

**Comment by KeiranY** [comment]
Also the ability to export and import replays, possibly using zip files
