### ISSUE TITLE
Is this app dead?

### ISSUE THREAD

**Issue by blueberry-bytes** [KcYoung1997/PubgReplayManager#10]
Hi, I've fixed some things, the most important is that replays are no longer damaged after using Locked checkbox and I've added new map names. Besides I've refreshed the code a little. Can I push it here or is it better to make a fork?

**Comment by blueberry-bytes** [comment]
And I have more ideas to improve it. Switching to WPF (nicer looks), adding position and kills etc.

**Comment by Adelscott** [comment]
@blueberry-bytes fork it maybe ?

**Comment by KeiranY** [comment]
Hey-o, yeah feel free to make a fork @blueberry-bytes - This project is years old and I've not touched the game in a similar length of time. Best of luck with your project!
