### ISSUE TITLE
Document replay format

### ISSUE THREAD

**Issue by Herbstein** [KcYoung1997/PubgReplayManager#6]
I would love for this project to be the base of a proper replay manager, that can actually show meta-info about any valid replay. For that we would need to start documenting the format of the replays. 

Initial findings (maybe):

- All checkpoints in the checkpoint folder has the total gameplay state at the time of serialization, probably for all players within the 1KM radius.
- It seems like it's using some kind of generic UE4 serialization. There's seemingly a lot of references to UE4 standard classes, such as `SkeletalMeshComponent`, supporting that claim.
- The first file we'll want to parse is probably `PUBG.replayinfo`. I think it contains the most general information, including the player name.

**Comment by Herbstein** [comment]
Also seems that the newest update, ahead of the 1.0 patch deployment, have been updated. That means replays from previous versions have been invalidated.

[Source](https://steamcommunity.com/games/578080/announcements/detail/3066253941346037760)

**Comment by victorp13** [comment]
PUBG.replayinfo indeed has a few useful parameters (Mode, ShouldKeep, LengthInMS) but I cannot seem to find my rank,  # of headshots, kills nor damage dealt, longest kill etc. This must be in another file, but they seem pretty unreadable. I tried reverse engineering the hex code based on known numbers (variances between save games) but to no avail.

A good replay manager tool would need a way to immediately open the game with the selected replay. I am curious: Did you guys find launch options for TSLGame.exe to start a replay directly?

**Comment by Herbstein** [comment]
I have only found the same as you. I can't even find the steamID or username of a squad mate I played duo with. I ran some statistics on some files. It seems that some a straight binary data, like PUBG.demo, while others are heavily skewed towards alphanumerics. I believe we should start by looking at the skewed files first. 

I just realized while typing this - could they be using some kind of cipher or shift? Mapping some letters to other letters? The skewed files look like completely random letters and numbers, but an encrypted file would look like random noise. 

I screen capped two analysis and wrote a few thoughts for each. [Imgur](https://imgur.com/a/M9BXG)

**Comment by KeiranY** [comment]
So first of all sorry for my absense from this project, I will be continuing to work on it but I am currently at home for the holidays with no real environment to develop from and am spending time with family.

As a response to your initial findings and the use of the `PUBG.replayinfo` file, if you look [here](https://github.com/KcYoung1997/PubgReplayManager/blob/be921ce0ea5139a515e8df86eddff503dd5c7c87/PubgReplayManager/Program.cs#L38) you will see that this is the file I originally used for getting the information to populate the dataGridView, although I didn't parse all the feilds from it as not all were considered useful.

The rest of the replay files seem to be created by the [UE4 standard replay system](https://docs.unrealengine.com/latest/INT/Engine/Replay/), it uses a fake network adapter and saves network states to files. I can't at the moment find much information about reverse engineering this at this time but I'll take a better look in the future.

In the `Events` folder there are four types of events that I can see (I've uploaded examples in the links but they may be out of date as I don't have access to replays fom the new release:

1. [Event](https://gist.github.com/KcYoung1997/4069c6060ea482148086968b3a571d0c) files that contain checkpoints that trigger every 30 seconds, basically useless to us as we know the game length already.
2. [Groggy](https://gist.github.com/KcYoung1997/df404531c94831d342c09a6f390aaf7d) files that are records of a player being downed, this contains a timestamp their steam ID in the "meta" tag .
3. [Kill](https://gist.github.com/KcYoung1997/3ef19ca65325842513a29d8ce2ee8119) files that are functionally identical to Groggy files but reference kills, of course.
4. [ReplaySummary] files, one for the start of the match and one for the end, contains the games `FriendlyName` from `PUBG.replayinfo`

The `Data` folder contains the same files, minus checkpoints, but with a set value added or removed from every character, these files are the ones seen in the first image of the previous posts analysis.
[Groggy](https://gist.github.com/KcYoung1997/64b3517cda593cc9431a6fbc9845c6f4), [Kill](https://gist.github.com/KcYoung1997/9c7f24c1fd3caa5061bb6f0d3b087c2d), [ReplaySummary](https://gist.github.com/KcYoung1997/bbff76a841849585b8f3e7b188645f71)

Match used for this info:
[match.zip](https://github.com/KcYoung1997/PubgReplayManager/files/1590726/match.zip)

**Comment by Herbstein** [comment]
I had loosely gathered some of that, but it's good to have it completely clear. Actually parsing the whole replay seems pretty out our scope, but loosely reading the Kill and Groggy files, and parsing the amount of kills a player makes, the times they are downed, etc. could be very useful for the user. 

How do we know who knocks someone out, or kills them? I'm pretty sure the game doesn't simulate it when parsing the replay, so that will have to be available from just the meta-data in the files. Each kill does not store that though. Maybe it's stored in the incomprehensible checkpoint files?

I gotta admit, I had just completely missed that the files in the `events` folder were readable in plaintext. That demystifies it quite a bit to me.

**Comment by EpicKitten** [comment]
I was doing a search on Reddit to find my old post and found yours. 
I did figure out how to decipher alot of the replays if anyone is still interested (https://github.com/EpicKitten/PUBG-Replay-Manager)
Sorry for kinda stealing the name/idea :(

**Comment by Herbstein** [comment]
That's some good work. I just completely stopped looking into this after the owner stopped doing anything with this anyway :P
