### ISSUE TITLE
Settings do not save

### ISSUE THREAD

**Issue by KeiranY** [KcYoung1997/PubgReplayManager#8]
Although they are [set](https://github.com/KcYoung1997/PubgReplayManager/blob/44e6ea6b294a909fccda781460e44cac86ff4502/PubgReplayManager/Form1.cs#L25-L32) and [saved](https://github.com/KcYoung1997/PubgReplayManager/blob/44e6ea6b294a909fccda781460e44cac86ff4502/PubgReplayManager/Form1.cs#L291) directory settings do not seem to be stored. This may be a personal issue as I'm currently using Linux but I can see that the user settings file is being created succesfully.

**Comment by Herbstein** [comment]
How does this manifest? I haven't had to do anything manually, and it seems to just work perfectly on my system.

**Comment by KeiranY** [comment]
For me being on a system without PUBG at the moment I have to set the replays location each time. I'd also like the user to be able to set their own backups location eventually if they want.
